In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [7]:
independent=dataset[['Age', 'EstimatedSalary','Gender_Male']]

In [8]:
independent

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [9]:
dependent=dataset['Purchased']

In [10]:
dependent

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [5, 10, 15, 20, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 5],
    'max_features': [None, 'sqrt', 'log2'],
    'class_weight': [None, 'balanced']
}


grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
grid.fit(X_train, y_train)

Fitting 5 folds for each of 810 candidates, totalling 4050 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'class_weight': [None, 'balanced'],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [5, 10, 15, 20, None],
                         'max_features': [None, 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 5],
                         'min_samples_split': [2, 5, 10]},
             scoring='f1_weighted', verbose=3)

In [17]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_

In [18]:
re

{'mean_fit_time': array([0.00367904, 0.00377049, 0.00269051, 0.00216331, 0.00255284,
        0.00212836, 0.0022964 , 0.00198398, 0.00208344, 0.00211458,
        0.00183859, 0.00190902, 0.0019732 , 0.00199413, 0.00186357,
        0.0018487 , 0.00199099, 0.00175743, 0.00194368, 0.00185957,
        0.00190043, 0.00193338, 0.0017076 , 0.00146523, 0.00180283,
        0.00183029, 0.00203295, 0.00165706, 0.00215406, 0.00200925,
        0.0019557 , 0.00220199, 0.00189638, 0.00200825, 0.00191483,
        0.00192003, 0.00196152, 0.00151873, 0.00204639, 0.00187759,
        0.00181437, 0.00201206, 0.00175858, 0.00172615, 0.00197191,
        0.00170379, 0.00169482, 0.0018683 , 0.00186901, 0.00195117,
        0.00189323, 0.00144696, 0.00166712, 0.00212069, 0.0020298 ,
        0.00210319, 0.00209947, 0.00187912, 0.00189877, 0.00212412,
        0.00176654, 0.00160413, 0.00174184, 0.0016315 , 0.00230885,
        0.00192208, 0.00171914, 0.00198331, 0.00189142, 0.00222254,
        0.00208554, 0.00181227, 0.00194526, 0.00223479, 0.00216775,
        0.00190005, 0.00256414, 0.00190992, 0.00199537, 0.00200229,
        0.00185189, 0.00209575, 0.00190635, 0.00175705, 0.00195341,
        0.00191259, 0.00201812, 0.00184479, 0.00187225, 0.00189271,
        0.00203624, 0.00166183, 0.00198994, 0.00201387, 0.00185976,
        0.00201306, 0.00191221, 0.00190201, 0.00192361, 0.00206676,
        0.00202346, 0.0019958 , 0.00221443, 0.00187531, 0.00198245,
        0.00177135, 0.00176992, 0.00184808, 0.00219684, 0.00192351,
        0.00232782, 0.00206804, 0.00211391, 0.00218406, 0.0019918 ,
        0.00199885, 0.00195818, 0.00244184, 0.00208702, 0.00166879,
        0.00192461, 0.00216446, 0.00156422, 0.00228229, 0.00165014,
        0.00162425, 0.00218306, 0.00173697, 0.00166345, 0.00193744,
        0.00198274, 0.00183048, 0.00201921, 0.00164781, 0.00197139,
        0.00218058, 0.00206718, 0.00235057, 0.00193543, 0.00214782,
        0.00214391, 0.00196967, 0.0021091 , 0.00196099, 0.00186257,
        0.00201764, 0.0020196 , 0.00232391, 0.0026298 , 0.00219455,
        0.0018065 , 0.00194283, 0.00187855, 0.00225592, 0.0019999 ,
        0.00222149, 0.00245209, 0.00204539, 0.00265231, 0.00182667,
        0.00192375, 0.00208187, 0.00245442, 0.00215707, 0.00251217,
        0.0020782 , 0.00245523, 0.00241404, 0.00204082, 0.00203114,
        0.00219231, 0.0022182 , 0.00207162, 0.0017611 , 0.00200381,
        0.00210543, 0.00225234, 0.00201988, 0.00232086, 0.00183578,
        0.00193567, 0.00195556, 0.001688  , 0.0022624 , 0.00187726,
        0.00211654, 0.00203991, 0.00207429, 0.00186739, 0.00198007,
        0.00226669, 0.00183158, 0.00268135, 0.00193629, 0.00213637,
        0.00175114, 0.00208473, 0.0023016 , 0.00200863, 0.00164599,
        0.00185142, 0.00202937, 0.00194974, 0.00226016, 0.00208697,
        0.00198984, 0.00237579, 0.00171742, 0.00201893, 0.00194564,
        0.00208178, 0.00173373, 0.00182819, 0.00207667, 0.0019237 ,
        0.00163674, 0.00252786, 0.00177798, 0.00219421, 0.0019382 ,
        0.00227108, 0.00216975, 0.00217733, 0.00191417, 0.00269437,
        0.00195398, 0.00219951, 0.00206847, 0.00167646, 0.00234923,
        0.00173306, 0.00203714, 0.00158086, 0.00158458, 0.00194774,
        0.00218482, 0.00195365, 0.00216241, 0.0018744 , 0.00196877,
        0.00172238, 0.00193901, 0.00205798, 0.00234394, 0.0020905 ,
        0.00243869, 0.00211225, 0.00222898, 0.00213494, 0.00199776,
        0.00223846, 0.00207572, 0.00224981, 0.0017539 , 0.00202656,
        0.00210404, 0.00187535, 0.00190506, 0.00219221, 0.00152369,
        0.00194454, 0.00230312, 0.00184207, 0.00185223, 0.00204892,
        0.00189719, 0.00175796, 0.0020977 , 0.00197477, 0.00214367,
        0.00177422, 0.00185657, 0.00197763, 0.00196185, 0.00208354,
        0.00178576, 0.00178194, 0.00205059, 0.00189323, 0.00199699,
        0.00202408, 0.0018836 , 0.0019278 , 0.00220199, 0.00224786,
        0.00183139, 0.0017036 , 0.00174732, 0.0017983 , 0.00172839,
        0.00181155, 0.00233512, 0.00188012, 0.00229392, 0.00173292,
        0.00200133, 0.00211916, 0.0021121 , 0.00172119, 0.00203595,
        0.00214763, 0.00203142, 0.00203218, 0.0020165 , 0.00199399,
        0.00276089, 0.00210042, 0.00195913, 0.00169044, 0.00185199,
        0.00233378, 0.00208068, 0.00195298, 0.00197821, 0.00232692,
        0.00205798, 0.00218258, 0.00184436, 0.00196209, 0.00197186,
        0.0020905 , 0.0019237 , 0.00202184, 0.00212669, 0.00215712,
        0.00238128, 0.00242567, 0.0018599 , 0.00198936, 0.00219002,
        0.00213718, 0.00182271, 0.00212479, 0.00221615, 0.00171919,
        0.00188975, 0.00162592, 0.00243664, 0.00213404, 0.00171461,
        0.00197968, 0.00180449, 0.00208998, 0.00179615, 0.00210853,
        0.00220022, 0.00210586, 0.0020515 , 0.00190377, 0.00253377,
        0.00199037, 0.00234227, 0.00246253, 0.00218477, 0.00223069,
        0.00233521, 0.00207114, 0.00220408, 0.00183492, 0.00216756,
        0.00196676, 0.00202637, 0.00220833, 0.00199957, 0.00201631,
        0.00204201, 0.00204501, 0.00174356, 0.00196781, 0.00188775,
        0.00182929, 0.00249758, 0.0020987 , 0.00206251, 0.00239024,
        0.00217032, 0.00184178, 0.00243821, 0.0021997 , 0.00246868,
        0.00206895, 0.00213594, 0.00220118, 0.00234346, 0.00237966,
        0.00215311, 0.00210261, 0.00187607, 0.00218658, 0.00182824,
        0.00210538, 0.00181704, 0.0023684 , 0.00185647, 0.00196562,
        0.00195637, 0.00195236, 0.00191755, 0.00204706, 0.00202475,
        0.00219231, 0.00225315, 0.00203896, 0.00232663, 0.00211658,
        0.00297856, 0.00339766, 0.00267196, 0.00350189, 0.00269575,
        0.00303473, 0.00337677, 0.00247822, 0.00281477, 0.00273762,
        0.00270104, 0.00304112, 0.00266304, 0.00307641, 0.00301371,
        0.00282216, 0.00334296, 0.00274086, 0.00275493, 0.00286937,
        0.00260611, 0.0030427 , 0.00288701, 0.00276546, 0.00288634,
        0.0031589 , 0.0029563 , 0.00310235, 0.00296159, 0.00284076,
        0.00319266, 0.00275574, 0.00257783, 0.00283117, 0.00352926,
        0.00293932, 0.00305982, 0.00327959, 0.0030355 , 0.00282407,
        0.00303168, 0.00292506, 0.0027523 , 0.00288024, 0.00264163,
        0.00282469, 0.00287585, 0.00311146, 0.00269356, 0.00272784,
        0.00293884, 0.00272336, 0.00308208, 0.0030057 , 0.00319767,
        0.00298519, 0.00325089, 0.00302768, 0.00320463, 0.00315008,
        0.00316539, 0.00330849, 0.0032053 , 0.00303049, 0.0027791 ,
        0.00262423, 0.00336928, 0.00262022, 0.00283809, 0.00289254,
        0.00247197, 0.00281167, 0.00316868, 0.00276761, 0.00328832,
        0.00296659, 0.00283809, 0.00333405, 0.00291643, 0.00290098,
        0.00308361, 0.00305362, 0.00287519, 0.0033143 , 0.00351233,
        0.00334716, 0.00297985, 0.00290718, 0.00287375, 0.00306702,
        0.0033834 , 0.00267859, 0.00276656, 0.00292521, 0.00299597,
        0.00301938, 0.00296302, 0.00338707, 0.00311823, 0.00312099,
        0.00312004, 0.00301046, 0.00319262, 0.00308971, 0.00283341,
        0.0033639 , 0.00271883, 0.00279646, 0.00275731, 0.00288186,
        0.00333829, 0.00295639, 0.00336728, 0.00341783, 0.00324545,
        0.00311556, 0.00274687, 0.00304265, 0.00301619, 0.00270729,
        0.00288281, 0.00277987, 0.00301785, 0.00302339, 0.00315356,
        0.0027102 , 0.00272541, 0.00279665, 0.0029057 , 0.00243778,
        0.0030334 , 0.00319476, 0.00323615, 0.00310388, 0.00301147,
        0.00289822, 0.00294261, 0.00330553, 0.00324678, 0.00316029,
        0.00354414, 0.00329084, 0.00288796, 0.00290895, 0.00317273,
        0.00298753, 0.00293226, 0.00284662, 0.00311961, 0.00281472,
        0.00283694, 0.00280676, 0.00280685, 0.00280046, 0.00348959,
        0.00312333, 0.00375881, 0.00312214, 0.00309343, 0.00278873,
        0.00305529, 0.00269432, 0.0033525 , 0.00313053, 0.00315576,
        0.00321689, 0.00330653, 0.00357862, 0.00271654, 0.00275159,
        0.00342584, 0.0029623 , 0.00326638, 0.00295129, 0.00315337,
        0.00286269, 0.00284729, 0.00321078, 0.00294638, 0.00289493,
        0.00348949, 0.00241675, 0.00295167, 0.00306239, 0.003232  ,
        0.0034215 , 0.00281587, 0.00318947, 0.00304461, 0.00325832,
        0.0035327 , 0.00328088, 0.00346956, 0.00340133, 0.00306225,
        0.00296073, 0.00317817, 0.00315242, 0.003373  , 0.00281186,
        0.00274677, 0.00269465, 0.0033906 , 0.0032104 , 0.00355639,
        0.00334578, 0.00259867, 0.00310855, 0.00329428, 0.00278234,
        0.00298719, 0.00383496, 0.0030829 , 0.00236845, 0.00334682,
        0.00304055, 0.00363555, 0.00316248, 0.00315237, 0.00287757,
        0.00324831, 0.00306969, 0.0032784 , 0.00314627, 0.00260615,
        0.00294933, 0.00277328, 0.00279689, 0.00300965, 0.00277376,
        0.00275321, 0.00260186, 0.00291467, 0.002982  , 0.00307775,
        0.00301614, 0.00304708, 0.00293097, 0.00268884, 0.002736  ,
        0.00270824, 0.00277252, 0.00202742, 0.00301385, 0.00254455,
        0.00321426, 0.00306706, 0.0025404 , 0.00293365, 0.0029943 ,
        0.00304036, 0.0026495 , 0.00276308, 0.00283732, 0.00237212,
        0.0030498 , 0.00275736, 0.00278759, 0.0026875 , 0.00269103,
        0.00281014, 0.00282397, 0.00290337, 0.00282135, 0.00272946,
        0.00302968, 0.00297694, 0.00288873, 0.00265698, 0.00274286,
        0.00249181, 0.00285592, 0.00248919, 0.00265841, 0.00291047,
        0.00297403, 0.00320063, 0.00297041, 0.00256667, 0.00282383,
        0.00289783, 0.00279274, 0.00308561, 0.00239305, 0.0026876 ,
        0.00278502, 0.00281925, 0.00274205, 0.00240502, 0.0024157 ,
        0.0024344 , 0.00297832, 0.00276985, 0.00247951, 0.00249052,
        0.00298877, 0.00267949, 0.00266581, 0.00318723, 0.00304813,
        0.00305095, 0.00319033, 0.00314441, 0.00305972, 0.00278916,
        0.00309958, 0.00285635, 0.00300474, 0.00287914, 0.00299411,
        0.00258303, 0.00255766, 0.00275159, 0.00273309, 0.00290127,
        0.00292616, 0.00291662, 0.00312357, 0.0026679 , 0.00275116,
        0.00282631, 0.00281305, 0.00277371, 0.00277615, 0.00247483,
        0.00273027, 0.00281796, 0.00285416, 0.00328078, 0.00285172,
        0.00311937, 0.00314546, 0.00328655, 0.00297294, 0.00250425,
        0.00322051, 0.0028389 , 0.00304832, 0.00291553, 0.00295877,
        0.0029809 , 0.00314045, 0.00334096, 0.00274496, 0.00304594,
        0.00259733, 0.00256476, 0.00304427, 0.00252123, 0.00294299,
        0.00260262, 0.00262437, 0.0029387 , 0.00312285, 0.00313392,
        0.00258451, 0.00293884, 0.00304174, 0.00321093, 0.00347161,
        0.00341802, 0.00293584, 0.00256076, 0.00259781, 0.00226974,
        0.00282559, 0.00342989, 0.00318136, 0.00293531, 0.00261793,
        0.00264244, 0.00263023, 0.00347366, 0.00267825, 0.00322914,
        0.00282245, 0.00291853, 0.00298562, 0.00304589, 0.00306239,
        0.00315084, 0.00308752, 0.00283656, 0.0029952 , 0.00276413,
        0.00322652, 0.00321474, 0.00317278, 0.0029449 , 0.0031394 ,
        0.00286503, 0.00312114, 0.00295429, 0.00294633, 0.00316067,
        0.00284667, 0.00296259, 0.00302305, 0.00254221, 0.0029233 ,
        0.00308905, 0.00295186, 0.00300875, 0.00292554, 0.00305228]),
 'std_fit_time': array([9.36896002e-04, 3.58807386e-04, 3.55680293e-04, 2.50491441e-04,
        2.61082283e-04, 4.24186494e-04, 1.01318235e-04, 4.86760561e-04,
        2.59199776e-04, 2.43487612e-04, 3.13834809e-04, 2.79242045e-04,
        2.08191898e-04, 3.26037525e-04, 4.51983693e-04, 2.77260901e-04,
        3.79202675e-04, 3.20799597e-04, 3.02064225e-04, 2.31757409e-04,
        2.91102700e-04, 4.12781858e-04, 3.58971405e-04, 3.08787999e-04,
        2.12852470e-04, 3.48837014e-04, 4.06385133e-04, 1.65820243e-04,
        3.03841909e-04, 2.81274579e-04, 3.71306007e-04, 6.77177087e-04,
        3.59708962e-04, 2.62687223e-04, 3.30428698e-04, 4.03908584e-04,
        2.02047580e-04, 3.29987679e-04, 3.38937227e-04, 3.08769325e-04,
        2.73355359e-04, 2.89407764e-04, 3.41588248e-04, 5.13192943e-04,
        1.86705308e-04, 1.98471540e-04, 3.97195896e-04, 2.04203441e-04,
        4.09998370e-04, 2.22704976e-04, 6.63473497e-04, 1.46271226e-04,
        2.72658372e-04, 1.54914361e-04, 4.25190980e-04, 7.20993867e-05,
        3.99853373e-04, 3.32728024e-04, 2.56727682e-04, 4.17585208e-04,
        4.30600181e-04, 3.82005506e-04, 3.14537542e-04, 3.39482841e-04,
        9.10428459e-04, 3.43241795e-04, 3.93904945e-04, 2.19155499e-04,
        1.73821593e-04, 2.26312813e-04, 4.09791690e-04, 1.83946224e-04,
        1.94036811e-04, 1.87238876e-04, 4.83180492e-04, 1.33730645e-04,
        1.07924172e-03, 2.63895719e-04, 6.95264551e-05, 8.10260411e-05,
        4.25420088e-04, 4.89254267e-04, 1.37404034e-04, 5.39039586e-04,
        2.23787527e-04, 2.25695444e-04, 1.55265135e-04, 2.56632970e-04,
        2.05224608e-04, 2.54282177e-04, 4.57690650e-05, 2.33056589e-04,
        4.67729858e-05, 5.74465893e-05, 2.80929396e-04, 3.52621565e-04,
        4.70932161e-05, 3.34436892e-04, 5.57780049e-05, 1.20622328e-04,
        4.11810440e-04, 3.15745602e-04, 4.46309671e-04, 2.72633646e-04,
        9.34453632e-05, 2.86854256e-04, 2.42365244e-04, 3.05616932e-04,
        4.56088483e-04, 2.37862482e-04, 7.24811579e-04, 1.39696768e-04,
        3.52728523e-04, 3.71130193e-04, 6.58980327e-05, 2.03671178e-04,
        2.29336783e-04, 4.35456543e-04, 4.32708995e-04, 2.13444190e-04,
        3.05284898e-04, 3.99595587e-04, 2.32926991e-04, 5.65285224e-04,
        2.47694640e-04, 2.69146914e-04, 3.74094678e-04, 2.64409218e-04,
        4.59138970e-04, 1.94675239e-04, 3.56284588e-04, 2.64767137e-04,
        4.96002276e-04, 5.33475998e-04, 2.81939163e-04, 2.98344515e-04,
        3.86176063e-04, 5.39905239e-04, 2.36384941e-04, 1.69517092e-04,
        3.73938436e-04, 4.75641554e-04, 5.32891252e-04, 3.29914185e-04,
        2.72079012e-04, 2.93058454e-04, 4.23371100e-04, 6.98922369e-04,
        5.78865431e-04, 7.68712370e-04, 3.33628515e-04, 2.60082015e-04,
        4.59155743e-04, 8.33054072e-04, 2.77168070e-04, 8.36524080e-04,
        3.81483119e-04, 3.62502666e-04, 5.43993807e-04, 6.21436636e-04,
        3.48160567e-04, 3.37267465e-04, 6.22255384e-04, 1.58162839e-04,
        2.58935371e-04, 2.92843033e-04, 4.06344556e-04, 1.03140924e-04,
        3.12858576e-04, 5.01558426e-04, 4.48490770e-04, 5.23957544e-04,
        4.39555259e-04, 2.03562481e-04, 1.52593076e-04, 1.88412560e-04,
        2.63051012e-04, 4.51969592e-04, 3.47995895e-04, 3.02609419e-04,
        3.19355841e-04, 4.29942132e-04, 2.48162706e-04, 6.33812489e-04,
        1.82845408e-04, 3.88969886e-04, 9.09647338e-05, 1.03436784e-04,
        2.28333492e-04, 3.62076964e-04, 5.20794166e-04, 2.61096034e-04,
        3.23677948e-04, 4.04260017e-04, 4.90481585e-04, 2.90306490e-04,
        2.73451206e-04, 1.87257941e-04, 3.32734611e-04, 3.10332437e-04,
        3.15430163e-04, 3.02328649e-04, 1.51264847e-04, 6.31946934e-04,
        1.36703949e-04, 1.58426159e-04, 5.12900717e-04, 3.48838064e-04,
        1.96876587e-04, 5.66151162e-04, 3.16241718e-04, 4.22022447e-04,
        3.44633574e-04, 7.36619215e-04, 3.48384994e-04, 3.33290686e-04,
        6.08979665e-04, 2.68230103e-04, 3.80053825e-04, 2.89007245e-04,
        4.34742314e-04, 2.42578953e-04, 3.40745364e-04, 2.92458290e-04,
        8.10914520e-04, 3.21124659e-04, 2.62687059e-04, 4.24351702e-04,
        2.71311988e-04, 9.12402435e-04, 2.70916491e-04, 2.01875171e-04,
        3.46067523e-04, 2.55737481e-04, 1.60615828e-04, 3.17715686e-04,
        1.65374757e-04, 1.21978487e-04, 1.42935499e-04, 3.79605824e-04,
        4.28251575e-04, 4.41318017e-04, 2.32490288e-04, 1.51751536e-04,
        3.95050316e-04, 2.26810270e-04, 3.26063278e-04, 2.10140897e-04,
        1.92922245e-04, 4.59540698e-04, 7.52878314e-04, 4.31026778e-04,
        3.26155835e-04, 2.60821365e-04, 4.78072402e-04, 2.05231788e-04,
        5.22992061e-04, 2.91957490e-04, 7.74032876e-04, 2.84652909e-04,
        3.56903391e-04, 6.05627475e-04, 2.86630437e-04, 3.62721548e-04,
        2.66325373e-04, 1.70333722e-04, 2.83538641e-04, 1.59636264e-04,
        3.81591611e-04, 3.11447364e-04, 2.45612965e-04, 3.52183707e-04,
        4.17510441e-04, 4.02366134e-04, 3.50182080e-04, 3.13946196e-04,
        3.97805640e-04, 3.87605712e-04, 2.19561864e-04, 3.87445934e-04,
        1.60658080e-04, 2.66622575e-04, 2.19293433e-04, 4.80044413e-04,
        3.43589427e-04, 9.37387875e-05, 2.92325237e-04, 2.65141845e-04,
        2.14766397e-04, 1.64971089e-04, 5.32898782e-04, 5.87525775e-04,
        3.30183872e-04, 1.39595461e-04, 3.18720810e-04, 3.74126003e-04,
        5.28421262e-04, 2.63371904e-04, 3.71224983e-04, 2.47153241e-04,
        2.05678246e-04, 1.43688894e-04, 3.36953684e-04, 2.71809661e-04,
        3.37295158e-04, 4.81683234e-04, 2.47967307e-04, 1.67188410e-04,
        2.89978135e-04, 2.13597628e-04, 3.46472603e-04, 4.59514117e-04,
        1.51595570e-04, 6.24133237e-04, 5.08069072e-04, 4.81122313e-05,
        6.56915323e-04, 2.66353289e-04, 2.83936553e-04, 2.14516981e-04,
        6.54361174e-04, 1.90801406e-04, 1.83201643e-04, 2.18853815e-04,
        2.94661660e-04, 4.68126690e-04, 2.94020591e-04, 3.45589618e-04,
        2.39347033e-04, 1.54564512e-04, 3.54563074e-04, 2.30493139e-04,
        1.05830245e-04, 1.74404023e-04, 3.51994924e-04, 4.01779192e-04,
        2.10065067e-04, 2.61140382e-04, 4.48200611e-04, 3.16991954e-04,
        2.51997886e-04, 1.96770399e-04, 4.33244701e-04, 4.20360653e-04,
        8.68827398e-05, 4.30738267e-04, 2.10111388e-04, 4.83573692e-04,
        4.00897505e-04, 6.42273590e-04, 2.83939187e-04, 2.49290831e-04,
        2.51464071e-04, 4.37353981e-04, 1.39737811e-04, 4.60027486e-04,
        4.34263823e-04, 3.50680505e-04, 3.78889519e-04, 5.39468926e-04,
        2.87644339e-04, 2.49617644e-04, 4.73572393e-04, 3.85581548e-04,
        1.21038235e-04, 4.03007054e-04, 3.70230035e-04, 3.29947436e-04,
        1.38517756e-04, 4.69773797e-04, 2.69611446e-04, 7.16716936e-04,
        1.27441954e-04, 3.55354055e-04, 4.90967933e-04, 2.99505097e-04,
        2.32944591e-04, 4.50782557e-04, 3.43106400e-04, 6.32203710e-04,
        2.23409450e-04, 2.81437289e-04, 3.60808899e-04, 2.34113079e-04,
        4.07256620e-04, 5.52030743e-04, 3.25764663e-04, 3.14744688e-04,
        5.69708055e-04, 3.04971470e-04, 1.93277141e-04, 3.92916174e-04,
        6.87105773e-04, 1.95001948e-04, 3.49319186e-04, 3.97606157e-04,
        2.93055459e-04, 3.37185557e-04, 3.11335522e-04, 1.24130943e-04,
        4.85726936e-05, 2.79294583e-04, 3.42718228e-04, 3.42663145e-04,
        8.05052522e-05, 3.47120978e-04, 7.66771593e-04, 3.31012133e-04,
        3.98594681e-04, 3.75848765e-04, 1.50077222e-04, 3.75702820e-04,
        4.65710978e-04, 7.40059949e-04, 5.00666904e-04, 2.83547037e-04,
        7.09367381e-04, 4.03625758e-04, 3.73880064e-04, 2.41405168e-04,
        5.63446411e-04, 2.40376378e-04, 8.16831809e-04, 7.12934622e-04,
        1.01900112e-04, 3.44637281e-04, 3.72717379e-04, 5.88309504e-04,
        4.76200618e-04, 5.30869886e-04, 4.84137010e-04, 3.44616934e-04,
        4.91798606e-04, 4.28204159e-04, 4.36598440e-04, 2.91330880e-04,
        4.13885413e-04, 4.60858646e-04, 4.38990630e-04, 6.64418784e-04,
        5.06891101e-04, 4.85754376e-04, 5.52428198e-04, 7.89402906e-04,
        5.41698954e-04, 7.40147850e-04, 5.05192499e-04, 1.13858145e-03,
        2.40331443e-04, 3.28881519e-04, 8.13015963e-04, 4.69792576e-04,
        4.08817127e-04, 4.34251796e-04, 5.71386102e-04, 3.58509078e-04,
        4.16555144e-04, 6.12173721e-04, 4.68279348e-04, 4.80609208e-04,
        2.73545623e-04, 3.47381266e-04, 3.60132822e-04, 4.75699890e-04,
        3.85468523e-04, 1.64993760e-04, 4.24388698e-04, 4.33541461e-04,
        3.71117964e-04, 3.54545041e-04, 3.06075097e-04, 5.96166358e-04,
        4.93432580e-04, 3.47230789e-04, 2.60169730e-04, 2.25490610e-04,
        1.81042956e-04, 5.18383656e-04, 6.23220701e-04, 2.73803384e-04,
        8.64285027e-04, 5.15165615e-04, 3.47105453e-04, 1.58277230e-04,
        5.62192154e-04, 5.62375417e-04, 8.49114833e-04, 2.47868633e-04,
        7.46580246e-04, 5.23169106e-04, 3.56213124e-04, 5.00923837e-04,
        4.45789436e-04, 2.50538320e-04, 5.28461393e-04, 6.80533950e-04,

In [19]:
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [20]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'class_weight': 'balanced', 'criterion': 'entropy', 'max_depth': None, 'max_features': 'log2', 'min_samples_leaf': 5, 'min_samples_split': 10}: 0.9043535442887727

In [21]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[74 11]
 [ 2 47]]

In [22]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.97      0.87      0.92        85
           1       0.81      0.96      0.88        49

    accuracy                           0.90       134
   macro avg       0.89      0.91      0.90       134
weighted avg       0.91      0.90      0.90       134

In [23]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])#[:,1] : → all rows,1 → second column (index starts from 0),Give me all rows, but only column 1 (positive class probability)

0.9561824729891957

In [24]:
table=pd.DataFrame.from_dict(re)

In [25]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003679,0.000937,0.005343,0.000615,None,gini,5,None,1,2,"{'class_weight': None, 'criterion': 'gini', 'm...",0.787654,0.868752,0.850543,0.906166,0.923510,0.867325,0.047532,451
1,0.003770,0.000359,0.005664,0.000650,None,gini,5,None,1,5,"{'class_weight': None, 'criterion': 'gini', 'm...",0.787654,0.868752,0.850543,0.925272,0.923510,0.871146,0.051132,362
2,0.002691,0.000356,0.004944,0.000509,None,gini,5,None,1,10,"{'class_weight': None, 'criterion': 'gini', 'm...",0.787654,0.868752,0.870362,0.925272,0.943041,0.879016,0.054343,246
3,0.002163,0.000250,0.005481,0.000662,None,gini,5,None,2,2,"{'class_weight': None, 'criterion': 'gini', 'm...",0.787654,0.850809,0.832483,0.906166,0.903610,0.856144,0.044798,610
4,0.002553,0.000261,0.004477,0.000526,None,gini,5,None,2,5,"{'class_weight': None, 'criterion': 'gini', 'm...",0.787654,0.850809,0.850543,0.906166,0.903610,0.859757,0.043453,559
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,0.003089,0.000204,0.004656,0.000526,balanced,log_loss,None,log2,2,5,"{'class_weight': 'balanced', 'criterion': 'log...",0.774691,0.834012,0.833323,0.787943,0.943041,0.834602,0.059207,776
806,0.002952,0.000244,0.004713,0.000186,balanced,log_loss,None,log2,2,10,"{'class_weight': 'balanced', 'criterion': 'log...",0.814815,0.870047,0.815149,0.852044,0.962636,0.862938,0.054237,517
807,0.003009,0.000201,0.004671,0.000222,balanced,log_loss,None,log2,5,2,"{'class_weight': 'balanced', 'criterion': 'log...",0.814815,0.870047,0.777291,0.907402,0.981233,0.870158,0.071291,370
808,0.002926,0.000206,0.004672,0.000349,balanced,log_loss,None,log2,5,5,"{'class_weight': 'balanced', 'criterion': 'log...",0.851852,0.889022,0.852044,0.962636,0.981233,0.907358,0.054754,3
809,0.003052,0.000188,0.004305,0.000500,balanced,log_loss,None,log2,5,10,"{'class_weight': 'balanced', 'criterion': 'log...",0.843811,0.904977,0.833653,0.888646,0.962636,0.886744,0.046384,152